name: CI

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run unit tests and code analyzers
      run: ./gradlew check
